name: SonarQube-Backend

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Code auschecken
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # wichtig für SonarQube

      # 2️⃣ Java einrichten
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      # 3️⃣ SonarQube Cache
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # 4️⃣ Maven Cache
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # 5️⃣ Lokale Csound-JAR installieren 💡
      - name: Install local Csound JAR
        run: |
          mvn install:install-file \
            -Dfile=backend/lib/csound-6.18.1.jar \
            -DgroupId=org.csound \
            -DartifactId=csound \
            -Dversion=6.18.1 \
            -Dpackaging=jar

      # 6️⃣ Backend bauen + Sonar-Analyse
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: backend
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=akleinlo_SoundCrazifier_backend
